# Install and configure databases
---
- name: Setup pgsql | Create DB if not exists (pgsql)
  postgresql_db:
    name: "{{ bacula_dir_dbname }}"
    state: present
  register: bacula_database_pgsql_exists
  when:
  - bacula_dir_db_engine == "pgsql"
  - bacula_database_enable_changes
  tags:
  - db

- name: Setup pgsql | Create Tables in DB (pgsql)
  postgresql_db:
    name: "{{ bacula_dir_dbname }}"
    state: import
    target: "{{ bacula_dir_dbimport_pgsql_file }}"
  when:
  - bacula_dir_db_engine == "pgsql"
  - bacula_database_enable_changes
  - bacula_database_pgsql_exists.changed
  tags:
  - db

- name: Setup pgsql | Create User and grant usage (pgsql)
  # needs python-psycopg2 / python3-psycopg2
  postgresql_user:
    db: "{{ bacula_dir_dbname }}"
    name: "{{ bacula_dir_dbuser }}"
    # host: "%"
    host: "{{ bacula_dir_dbaddress }}"
    password: "{{ bacula_dir_dbpassword }}"
    priv: "CONNECT/ALL"
    state: "present"
    expires: infinity
  no_log: True
  when:
  - bacula_dir_db_engine == "pgsql"
  - bacula_database_enable_changes
  tags:
  - db
