# Install and configure databases
---
- name: Setup mysql | Create DB if not exists (mysql)
  mysql_db:
    name: "{{ bacula_dir_dbname }}"
    state: present
  register: bacula_database_mysql_exists
  when:
  - bacula_dir_db_engine == "mysql"
  tags:
  - db

- name: Setup mysql | Create Tables in DB (mysql)
  mysql_db:
    name: "{{ bacula_dir_dbname }}"
    state: import
    target: "{{ bacula_dir_dbimport_mysql_file }}"
  when:
  - bacula_dir_db_engine == "mysql"
  - bacula_database_mysql_exists.changed
  tags:
  - db

- name: Setup mysql | Create User and grant usage (mysql)
  # needs python-mysqldb or python3-mysqldb
  mysql_user:
    name: "{{ bacula_dir_dbuser }}"
    # host: "%"
    host: "{{ bacula_dir_dbaddress }}"
    password: "{{ bacula_dir_dbpassword }}"
    priv: "{{ bacula_dir_dbname }}.*:ALL"
    state: "present"
  no_log: True
  when:
  - bacula_dir_db_engine == "mysql"
  tags:
  - db
